language: ruby
script : script/cibuild
sudo: false

rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
env:
  - ""
  - JEKYLL_VERSION=3.0
  - JEKYLL_VERSION=2.0
matrix:
  include:
    - # GitHub Pages
      rvm: 2.1.1
      env: GH_PAGES=true
    - # Ruby 1.9
      rvm: 1.9
      env: JEKYLL_VERSION=2.0
